[package]
name = "zenbook-duo-linux"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "5.0"
futures = "*"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
toml = "0.8"
udev = "0.7.0"
